In [2]:
import numpy as np
import math

In [3]:
"""
    Generate a sequence of outputs and corresponding states based on provided probability matrices

    Parameters:
    states (list): list of state names as strings, same order as probability matrices
                   (ex: ["A", "B", "C"])
    transition_matrix: see above image
    n (int): length of sequence to output

    Returns:
    two lists, one with the outputs and the other with the corresponding states
"""
def e_machine(states, transition_matrix, n):
    output_states = []
    outputs = []

    # pick a random state to start with
    state_index = np.random.choice(len(states))
    output_states.append(states[state_index])

    for i in range(n):
        # get column of probabilities corresponding to state
        state_prob = transition_matrix[state_index]

        # select transition
        result = np.random.choice(len(state_prob), p=state_prob)

        # figure out output and state corresponding to transition
        output = math.floor(result/len(states))
        state_index = result % len(states)

        output_states.append(states[state_index])
        outputs.append(output)
    
    return output_states, outputs

In [4]:
# even process
test_array_2 = [[0.5,0,0,0.5], [0,0,1,0]]
#[np.array([[0.5,0], [0,0]]),np.array([[0,1],[0.5,0]])]
states, outputs = e_machine(["A", "B"], test_array_2, 100)
print("states:", states)
print("outputs:", outputs)

states: ['B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A']
outputs: [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1]


- frequencies -> transition matrix
- np.random.direchlet
- implement simple reservoir


#### Calculating the transition matrices from the outputs and their corresponding states

Generating a long sequence of outputs for the even process

In [5]:
np.random.seed(5)
states, outputs = e_machine(["A", "B"], test_array_2, 10000)
print("states:", states)
print("outputs:", outputs)

states: ['B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', '

Calculating frequency of each transition/emission

In [6]:
transitions = {"(A,0 | A)" : 0,
               "(B,0 | A)" : 0,
               "(A,0 | B)" : 0,
               "(B,0 | B)" : 0,
               "(A,1 | A)" : 0,
               "(B,1 | A)" : 0,
               "(A,1 | B)" : 0,
               "(B,1 | B)" : 0}
for i, output in enumerate(outputs):
    key = f"({states[i+1]},{output} | {states[i]})"
    transitions[key] += 1

transitions

{'(A,0 | A)': 3349,
 '(B,0 | A)': 0,
 '(A,0 | B)': 0,
 '(B,0 | B)': 0,
 '(A,1 | A)': 0,
 '(B,1 | A)': 3325,
 '(A,1 | B)': 3326,
 '(B,1 | B)': 0}

Calculating probabilities

In [7]:
# P(A,0 | A)
transitions["(A,0 | A)"] /(transitions["(A,0 | A)"] + transitions['(B,1 | A)'])

0.5017980221756069

In [8]:
# P(B,1 | A)
transitions["(B,1 | A)"] /(transitions["(A,0 | A)"] + transitions['(B,1 | A)'])

0.4982019778243932

Generalizing the above into a function

In [9]:
def probability_rederivation(output_states, outputs):
    transitions = {}
    for i, output in enumerate(outputs):
        key = f"({output_states[i+1]}, {output} | {output_states[i]})"
        transitions[key] = transitions.get(key, 0) + 1

    # to store lists of transitions from state n
    states = {}
    for key in transitions.keys():
        state = key[-2]
        states[state] = states.get(state, []) + [[key, transitions[key]]]

    probabilities = {}
    for key in states.keys():
        total = sum(n for _, n in states[key])
        for transition, frequency in states[key]:
            probabilities[f"P{transition}"] = frequency/total
    
    return probabilities

In [10]:
states, outputs = e_machine(["A", "B"], test_array_2, 10000)
print("states:", states)
print("outputs:", outputs)
probability_rederivation(states, outputs)

states: ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', '

{'P(A, 0 | A)': 0.49329516347747476,
 'P(B, 1 | A)': 0.5067048365225253,
 'P(A, 1 | B)': 1.0}

Running with randomly generated distributions

In [11]:
def distribution_generator(num_states, num_outputs):
    alpha = [1] * num_states * num_outputs
    return np.random.dirichlet(alpha, num_states)

In [12]:
test_array_3 = distribution_generator(2,2)
print(test_array_3)
states, outputs = e_machine(["A", "B"], test_array_3, 10000)
print("states:", states)
print("outputs:", outputs)
probability_rederivation(states, outputs)

[[0.16350922 0.18253106 0.14223141 0.5117283 ]
 [0.06748213 0.11881787 0.11067507 0.70302494]]
states: ['B', 'B', 'A', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'A', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', '

{'P(B, 1 | B)': 0.6992004061429116,
 'P(A, 1 | B)': 0.11295849727122731,
 'P(B, 0 | B)': 0.1161314887676101,
 'P(A, 0 | B)': 0.07170960781825104,
 'P(B, 1 | A)': 0.5011786892975012,
 'P(B, 0 | A)': 0.18434700612918434,
 'P(A, 0 | A)': 0.1617161716171617,
 'P(A, 1 | A)': 0.15275813295615276}

#### Reservoir

$h_{t+1} = \tanh(Wh_t + vx_t)$

In [241]:
def weight_initialization(m, n):
    W = np.random.rand(m,n)
    W = np.random.rand(m, n)
    # find largest magnitude eigenvalue
    eig = max(abs(np.linalg.eigvals(W)))
    if eig > 1:
        W = W/eig
    W = W - np.mean(W)
    return W

In [221]:
# example of the normalized xavier weight initialization
from math import sqrt
from numpy import mean
# number of nodes in the previous layer
n = 10
# number of nodes in the next layer
m = 20
# calculate the range for the weights
lower, upper = -(sqrt(6.0) / sqrt(10)), (sqrt(6.0) / sqrt(10))
# generate random numbers
numbers = weight_initialization(5,5)
# scale to the desired range
scaled = lower + numbers * (upper - lower)
scaled = scaled/max(abs(np.linalg.eigvals(scaled)))
scaled = scaled - scaled.mean()
# summarize
print(lower, upper)
print(scaled.min(), scaled.max())
print(scaled.mean(), scaled.std())
print(max(abs(np.linalg.eigvals(scaled))))

-0.7745966692414833 0.7745966692414833
-0.9739650813640148 1.0698517499056928
0.0 0.647632345618623
1.029129403049064


In [261]:
mat = weight_initialization(5,5)
print(mat)
print("mean:", np.mean(mat))
print("std:", np.std(mat))
print("eig:", max(abs(np.linalg.eigvals(mat))))

[[ 0.21324305 -0.09978222 -0.07822041 -0.20364991 -0.18162534]
 [-0.03267536 -0.18606692 -0.20991479  0.19471605  0.20223195]
 [-0.13523752 -0.14707006  0.17545539 -0.14287956 -0.01404048]
 [-0.08153044 -0.19245612  0.3059988  -0.0195911  -0.19376993]
 [ 0.15692618  0.17662762  0.28580078  0.19790806  0.00960229]]
mean: -1.6653345369377347e-17
std: 0.1718029139319375
eig: 0.37666085558463386


In [14]:
def reservoir(h_t, x_t, W, v):
    return np.tanh(W @ h_t + v*x_t)

In [209]:
test_array_3 = distribution_generator(2,2)
print(test_array_3)
states, outputs = e_machine(["A", "B"], test_array_3, 10000)

[[0.01458381 0.25795833 0.38168814 0.34576972]
 [0.07563583 0.58391744 0.31074665 0.02970008]]


In [252]:
n = 5
x = outputs

# initial weights
W = weight_initialization(n, n)
v = np.random.rand(n,1)

# initialize hidden state
h_t = np.zeros_like(v)

for x_t in x:
    h_t = reservoir(h_t, x_t, W, v)

print(h_t)

[[-0.01112119]
 [ 0.14313282]
 [ 0.10040177]
 [-0.07253271]
 [-0.05044741]]


In [255]:
n = 5
x = outputs
# initialize hidden state
h_t = np.zeros_like(v)

for x_t in x[:700]:
    h_t = reservoir(h_t, x_t, W, v)

print(h_t)

[[-1.15749907e-05]
 [-1.35395126e-05]
 [-4.93415974e-05]
 [ 3.98343514e-05]
 [-3.14675561e-05]]
